# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/loginwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(571, 318)
        self.loginwidget = QtWidgets.QWidget(LoginWindow)
        self.loginwidget.setObjectName("loginwidget")
        self.labelUrlService = QtWidgets.QLabel(self.loginwidget)
        self.labelUrlService.setGeometry(QtCore.QRect(20, 20, 131, 41))
        self.labelUrlService.setObjectName("labelUrlService")
        self.labelPassword = QtWidgets.QLabel(self.loginwidget)
        self.labelPassword.setGeometry(QtCore.QRect(20, 100, 131, 41))
        self.labelPassword.setObjectName("labelPassword")
        self.loginButton = QtWidgets.QPushButton(self.loginwidget)
        self.loginButton.setGeometry(QtCore.QRect(20, 190, 121, 41))
        self.loginButton.setObjectName("loginButton")
        self.textEditUrlService = QtWidgets.QTextEdit(self.loginwidget)
        self.textEditUrlService.setGeometry(QtCore.QRect(20, 60, 531, 31))
        self.textEditUrlService.setObjectName("textEditUrlService")
        self.textEditPassword = QtWidgets.QTextEdit(self.loginwidget)
        self.textEditPassword.setGeometry(QtCore.QRect(20, 140, 531, 31))
        self.textEditPassword.setObjectName("textEditPassword")
        self.labelLoginStatus = QtWidgets.QLabel(self.loginwidget)
        self.labelLoginStatus.setGeometry(QtCore.QRect(150, 190, 281, 41))
        self.labelLoginStatus.setObjectName("labelLoginStatus")
        LoginWindow.setCentralWidget(self.loginwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 571, 27))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.labelUrlService.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">URL сервис</span></p></body></html>"))
        self.labelPassword.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Пароль</span></p></body></html>"))
        self.loginButton.setText(_translate("LoginWindow", "Войти"))
        self.labelLoginStatus.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#7c7c7c;\">Статус: не было входа</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
