# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/loginwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(573, 321)
        self.labelLoginStatus = QtWidgets.QLabel(LoginForm)
        self.labelLoginStatus.setGeometry(QtCore.QRect(20, 280, 281, 31))
        self.labelLoginStatus.setObjectName("labelLoginStatus")
        self.textEditUrlService = QtWidgets.QTextEdit(LoginForm)
        self.textEditUrlService.setGeometry(QtCore.QRect(20, 70, 531, 31))
        self.textEditUrlService.setObjectName("textEditUrlService")
        self.textEditPassword = QtWidgets.QTextEdit(LoginForm)
        self.textEditPassword.setGeometry(QtCore.QRect(20, 160, 531, 31))
        self.textEditPassword.setObjectName("textEditPassword")
        self.labelUrlService = QtWidgets.QLabel(LoginForm)
        self.labelUrlService.setGeometry(QtCore.QRect(20, 30, 131, 41))
        self.labelUrlService.setObjectName("labelUrlService")
        self.loginButton = QtWidgets.QPushButton(LoginForm)
        self.loginButton.setGeometry(QtCore.QRect(20, 220, 121, 41))
        self.loginButton.setObjectName("loginButton")
        self.labelPassword = QtWidgets.QLabel(LoginForm)
        self.labelPassword.setGeometry(QtCore.QRect(20, 120, 131, 41))
        self.labelPassword.setObjectName("labelPassword")

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Form"))
        self.labelLoginStatus.setText(_translate("LoginForm", "<html><head/><body><p><span style=\" font-size:10pt;\">Статус: не было входа</span></p></body></html>"))
        self.labelUrlService.setText(_translate("LoginForm", "<html><head/><body><p><span style=\" font-size:12pt;\">URL сервис</span></p></body></html>"))
        self.loginButton.setText(_translate("LoginForm", "Войти"))
        self.labelPassword.setText(_translate("LoginForm", "<html><head/><body><p><span style=\" font-size:12pt;\">Пароль</span></p></body></html>"))

